## prometheus.yml ##

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these extra labels to all time-series collected by this Prometheus instance.
  labels:
    monitor: 'dataman-monitor'

# rule_files:
#  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # Dataman
  - job_name: 'dataman'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    scrape_timeout: 5s

    static_configs:
      - targets: ['192.168.102.75:5014','192.168.102.76:5014','192.168.102.77:5014','192.168.102.78:5014','192.168.102.79:5014','192.168.102.80:5014','192.168.102.81:5014','192.168.102.82:5014','192.168.102.83:5014','192.168.102.84:5014','192.168.102.85:5014','192.168.102.86:5014','192.168.102.87:5014','192.168.102.88:5014','192.168.102.89:5014','192.168.102.90:5014']
        labels:
          group: 'mesos-slaves'
